name: jewelsim
channels:
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - automat=20.2.0
  - bcrypt=3.2.0
  - blas=1.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cffi=1.14.6
  - colorama=0.4.4
  - constantly=15.1.0
  - cryptography=3.4.7
  - cssselect=1.1.0
  - hyperlink=21.0.0
  - idna=3.2
  - incremental=17.5.0
  - iniconfig=1.1.1
  - intel-openmp=2021.2.0
  - itemadapter=0.2.0
  - libiconv=1.15
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.6.3
  - mkl=2021.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - more-itertools=8.8.0
  - numpy=1.20.2
  - numpy-base=1.20.2
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.2.5
  - parsel=1.5.2
  - pip=21.1.3
  - pluggy=0.13.1
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pyhamcrest=2.0.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pytest=6.2.4
  - pytest-runner=5.3.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytz=2021.1
  - pywin32=227
  - queuelib=1.5.0
  - scrapy=2.4.1
  - service_identity=18.1.0
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - toml=0.10.2
  - twisted=21.2.0
  - twisted-iocpsupport=1.0.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - w3lib=1.21.0
  - wheel=0.36.2
  - wincertstore=0.2
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=5.4.0

